# ---> This is for with TLS certicates Cert-Manager configuration <---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: netflix-app-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "netflix-app.devopscicd.xyz"
      secretName: netflix-app-tls # cert-manager will create this secret automatically
  rules:
    - host: "netflix-app.devopscicd.xyz"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: netflix-app
                port:
                  number: 3000

# ---> This is for without TLS certicates configuration <---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: netflix-app-ingress
# spec:
#   ingressClassName: nginx
#   rules:
#     - host: "netflix-app.devopscicd.xyz"
#       http:
#         paths:
#           - pathType: Prefix
#             path: "/"
#             backend:
#               service:
#                 name: netflix-app
#                 port:
#                   number: 3000
